apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  project: default
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.10.0
    helm:
      values: |-
        controller:
          config:
            use-forwarded-headers: true
            allow-snippet-annotations: "false"
            enable-owasp-modsecurity-crs: "true"
            modsecurity: "true"
            proxy-buffer-size: 32k
            proxy-buffers-number: "8"
            ssl-ciphers: ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
            ssl-protocols: TLSv1.2 TLSv1.3
          publishService:
            enabled: true
          extraVolumeMounts: []
            #  - name: copy-portal-skins
            #   mountPath: /var/lib/lemonldap-ng/portal/skins          
          extraVolumes: []
            #  - name: copy-portal-skins
            #    emptyDir: {}
          service:
            annotations:
              service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
              service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
              service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
          extraArgs:
            enable-ssl-passthrough: true
    chart: ingress-nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
