apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: https://releases.rancher.com/server-charts/stable
    targetRevision: 2.8.5
    helm:
      values: |-
        hostname: rancher.<DOMAIN>
        ingress:
          ingressClassName: nginx
          annotations:
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
            nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
          tls:
            source: letsEncrypt
          letsEncrypt:
            email: engineering@simplyagree.com
            ingress:
              class: nginx
    chart: rancher
  destination:
    server: https://kubernetes.default.svc
    namespace: cattle-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - Replace=true
      - PruneLast=true
