apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-toolkit-arc
  namespace: cattle-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k8s-toolkit-arc
  namespace: cattle-system
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
    verbs:
      - get
      - watch
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-toolkit-arc
  namespace: cattle-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: k8s-toolkit-arc
subjects:
  - kind: ServiceAccount
    name: k8s-toolkit-arc
    namespace: cattle-system
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '20'
  name: wait-rancher
  namespace: cattle-system
spec:
  template:
    spec:
      containers:
        - args:
            - wait-for
            - deployment
            - --namespace
            - cattle-system
            - --label
            - app.kubernetes.io/name=rancher
          image: public.ecr.aws/kubefirst/kubernetes-toolkit:0.0.8
          imagePullPolicy: IfNotPresent
          name: wait
      restartPolicy: OnFailure
      serviceAccountName: k8s-toolkit-arc
